# Generated by Django 5.2.8 on 2025-12-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
        ('organizers', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='organizers.event'),
            preserve_default=False,
        ),
    ]
