# Generated by Django 5.2.8 on 2025-12-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_event_enddatetime_event_startdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('festival', 'Festival'), ('theater', 'Theater'), ('tech', 'Tech'), ('other', 'Other')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
