# Generated by Django 5.2.8 on 2025-12-28 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='isMultiDay',
            field=models.BooleanField(default=False, help_text='Auto-calculated if event spans multiple days'),
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dayNumber', models.IntegerField(help_text='Day 1, Day 2, etc.')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('title', models.CharField(help_text="e.g., 'Day 1: Keynote Sessions'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schedule', models.JSONField(blank=True, help_text='JSON array of sessions for this day', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_days', to='organizers.event')),
            ],
            options={
                'ordering': ['date', 'startTime'],
                'unique_together': {('event', 'dayNumber')},
            },
        ),
    ]
