# Generated by Django 5.2.8 on 2025-12-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_remove_event_date_event_ismultiday_eventday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='isMultiDay',
            new_name='is_multi_day',
        ),
    ]
