# Generated by Django 5.2.8 on 2025-12-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0006_rename_ismultiday_event_is_multi_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
