# Generated by Django 5.2.8 on 2025-12-30 18:12

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0007_remove_event_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(help_text='Job title or role', max_length=255)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='speaker_image')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Talk'), ('panel', 'Panel Discussion'), ('workshop', 'Workshop'), ('break', 'Break'), ('networking', 'Networking'), ('lunch', 'Lunch'), ('registration', 'Registration'), ('other', 'Other')], default='talk', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField(help_text='Date of this schedule item')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizers.event')),
                ('event_day', models.ForeignKey(blank=True, help_text='Optional: Link to specific event day for multi-day events', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizers.eventday')),
                ('speakers', models.ManyToManyField(blank=True, related_name='schedules', to='organizers.speaker')),
            ],
            options={
                'ordering': ['date', 'start_time', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='speaker',
            index=models.Index(fields=['organizer', 'name'], name='organizers__organiz_645160_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['event', 'date', 'start_time'], name='organizers__event_i_7978ec_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['event_day', 'start_time'], name='organizers__event_d_5a4991_idx'),
        ),
    ]
