# Generated by Django 5.2.8 on 2025-12-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0008_speaker_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventday',
            name='schedule',
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
