# Generated by Django 5.2.8 on 2025-12-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0009_remove_eventday_schedule_event_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='short_description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
