# Generated by Django 5.2.8 on 2025-12-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer')], default='Attendee'),
        ),
    ]
